version: '3'
services:
  web:
    build: .
    # ports:
    #   - "3000:3000"
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1"
      interval: 5s
      timeout: 20s
      retries: 3
